theme: jekyll-theme-leap-day
title: Capstone Project Proposal
show_downloads: true
titles_from_headings:
  enabled: false
author:
  name: "Anastasia Hristian"
  href: "https://github.com/anhristian"
  